In [10]:
import numpy as np
import pandas as pd

In [ ]:
laptop_data = pd.read_csv("laptops_asus_data_   cellphones_full_v2.csv")

In [12]:
laptop_data.head()

,Name,Price,CPU,RAM,GPU,Storage,Screen Size,Screen Resolution,Panel,Screen frequency,Weight,URL
0,Laptop ASUS TUF Gaming F16 FX607VJ-RL034W,20.990.000đ,"Intel Core 5 210H 2.2 GHz (12MB Cache, up to 4...",16GB,NVIDIA GeForce RTX 3050 6GB GDDR6Intel Iris Xe...,512GB PCIe 4.0 NVMe M.2 SSD (2 Khe cắm M.2 hỗ ...,16 inches,1920 x 1200 pixels (WUXGA),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-tuf-gami...
1,Laptop ASUS VivoBook Go 14 E1404FA-NK177W,11.490.000đ,"AMD Ryzen 5 7520U (4MB cache, up to 4.3 GHz, 4...",16GB,AMD Radeon Graphics,SSD 512GB M.2 NVMe PCIe 3.0,14 inches,1920 x 1080 pixels (FullHD),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-vivobook...
2,Laptop ASUS Gaming Vivobook 16X K3605VC-RP431W,17.990.000đ,"Intel Core i5-13420H 2.1 GHz (12MB Cache, up t...",16GB,NVIDIA Geforce RTX 3050 4GB GDDR6 Intel UHD Gr...,512GB M.2 NVMe PCIe 4.0 SSD,16 inches,1920 x 1200 pixels (WUXGA),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-vivobook...
3,Laptop ASUS Gaming V16 V3607VU-RP343W,23.990.000đ,"Intel Core 5 210H 2.2 GHz (12MB Cache, up to 4...",16GB,NVIDIA GeForce RTX 4050 6GB GDDR6 (194 AI TOPs...,512GB M.2 NVMe PCIe 4.0 SSD,16 inches,1920 x 1200 pixels (WUXGA),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-gaming-v...
4,Laptop ASUS Vivobook 15 X1502VA-BQ885W,13.990.000đ,"Intel Core i5-13420H 2.1 GHz (12MB Cache, up t...",16GB,Intel HD Graphics,512GB M.2 NVMe PCIe 4.0 SSD,15.6 inches,1920 x 1080 pixels (FullHD),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-vivobook...

In [13]:
laptop_data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               790 non-null    object
 1   Price              790 non-null    object
 2   CPU                776 non-null    object
 3   RAM                657 non-null    object
 4   GPU                772 non-null    object
 5   Storage            762 non-null    object
 6   Screen Size        775 non-null    object
 7   Screen Resolution  766 non-null    object
 8   Panel              0 non-null      float64
 9   Screen frequency   0 non-null      float64
 10  Weight             0 non-null      float64
 11  URL                790 non-null    object
dtypes: float64(3), object(9)
memory usage: 74.2+ KB

In [19]:
# make the Price, RAM, Storage, ScreenSize, ScreenResolution columns numeric
laptop_data['Price'] = pd.to_numeric(laptop_data['Price'], errors='coerce')
laptop_data['RAM'] = pd.to_numeric(laptop_data['RAM'], errors='coerce')
laptop_data['Storage'] = pd.to_numeric(laptop_data['Storage'], errors='coerce')
laptop_data['ScreenSize'] = pd.to_numeric(laptop_data['Screen Size'], errors='coerce')
laptop_data['ScreenResolution'] = pd.to_numeric(laptop_data['Screen Resolution'], errors='coerce')

In [20]:
# Now we can run the info() method again to see the changes
laptop_data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790 entries, 0 to 789
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               790 non-null    object
 1   Price              0 non-null      float64
 2   CPU                776 non-null    object
 3   RAM                0 non-null      float64
 4   GPU                772 non-null    object
 5   Storage            0 non-null      float64
 6   Screen Size        0 non-null      float64
 7   Screen Resolution  766 non-null    object
 8   Panel              0 non-null      float64
 9   Screen frequency   0 non-null      float64
 10  Weight             0 non-null      float64
 11  URL                790 non-null    object
 12  ScreenSize         0 non-null      float64
 13  ScreenResolution   0 non-null      float64
dtypes: float64(9), object(5)
memory usage: 86.5+ KB

In [21]:
laptop_data.head()

,Name,Price,CPU,RAM,GPU,Storage,Screen Size,Screen Resolution,Panel,Screen frequency,Weight,URL,ScreenSize,ScreenResolution
0,Laptop ASUS TUF Gaming F16 FX607VJ-RL034W,NaN,"Intel Core 5 210H 2.2 GHz (12MB Cache, up to 4...",NaN,NVIDIA GeForce RTX 3050 6GB GDDR6Intel Iris Xe...,NaN,NaN,1920 x 1200 pixels (WUXGA),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-tuf-gami...,NaN,NaN
1,Laptop ASUS VivoBook Go 14 E1404FA-NK177W,NaN,"AMD Ryzen 5 7520U (4MB cache, up to 4.3 GHz, 4...",NaN,AMD Radeon Graphics,NaN,NaN,1920 x 1080 pixels (FullHD),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-vivobook...,NaN,NaN
2,Laptop ASUS Gaming Vivobook 16X K3605VC-RP431W,NaN,"Intel Core i5-13420H 2.1 GHz (12MB Cache, up t...",NaN,NVIDIA Geforce RTX 3050 4GB GDDR6 Intel UHD Gr...,NaN,NaN,1920 x 1200 pixels (WUXGA),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-vivobook...,NaN,NaN
3,Laptop ASUS Gaming V16 V3607VU-RP343W,NaN,"Intel Core 5 210H 2.2 GHz (12MB Cache, up to 4...",NaN,NVIDIA GeForce RTX 4050 6GB GDDR6 (194 AI TOPs...,NaN,NaN,1920 x 1200 pixels (WUXGA),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-gaming-v...,NaN,NaN
4,Laptop ASUS Vivobook 15 X1502VA-BQ885W,NaN,"Intel Core i5-13420H 2.1 GHz (12MB Cache, up t...",NaN,Intel HD Graphics,NaN,NaN,1920 x 1080 pixels (FullHD),NaN,NaN,NaN,https://cellphones.com.vn/laptop-asus-vivobook...,NaN,NaN

In [14]:
laptop_data['RAM'].value_counts(ascending=True)

RAM
128GB      1
24GB       4
64GB      11
4GB       54
32GB      94
8GB      238
16GB     255
Name: count, dtype: int64

In [16]:
laptop_data.count

<bound method DataFrame.count of                                                   Name               Price  \
0            Laptop ASUS TUF Gaming F16 FX607VJ-RL034W         20.990.000đ
1            Laptop ASUS VivoBook Go 14 E1404FA-NK177W         11.490.000đ
2       Laptop ASUS Gaming Vivobook 16X K3605VC-RP431W         17.990.000đ
3                Laptop ASUS Gaming V16 V3607VU-RP343W         23.990.000đ
4               Laptop ASUS Vivobook 15 X1502VA-BQ885W         13.990.000đ
..                                                 ...                 ...
785       Laptop ASUS ROG Strix Scar 16 G634JYR-RA132W  Liên hệ để báo giá
786         Laptop ASUS ExpertBook B1 B1402CVA-NK0062W  Liên hệ để báo giá
787           Laptop ASUS ROG Strix G18 G814JIR-N6108W  Liên hệ để báo giá
788  Laptop ASUS Gaming ROG Strix SCAR 18 G834JYR-R...  Liên hệ để báo giá
789  Laptop ASUS Gaming ROG Strix SCAR 16 G634JZR-N...        105.990.000đ

                                                   CPU   RAM  \
0    Intel Core 5 210H 2.2 GHz (12MB Cache, up to 4...  16GB
1    AMD Ryzen 5 7520U (4MB cache, up to 4.3 GHz, 4...  16GB
2    Intel Core i5-13420H 2.1 GHz (12MB Cache, up t...  16GB
3    Intel Core 5 210H 2.2 GHz (12MB Cache, up to 4...  16GB
4    Intel Core i5-13420H 2.1 GHz (12MB Cache, up t...  16GB
..                                                 ...   ...
785  Intel Core i9 14900HX 2.2 GHz (36MB Cache, up ...  64GB
786  Intel Core i5-1335U (1.3 GHz, 12M Cache, up to...   8GB
787  Intel Core i9 14900HX 2.2 GHz (36MB Cache, up ...  32GB
788                   Intel Raptor Lake i9-14900HX-T6K  64GB
789                       Intel Raptor Lake i9-14900HX  64GB

                                                   GPU  \
0    NVIDIA GeForce RTX 3050 6GB GDDR6Intel Iris Xe...
1                                  AMD Radeon Graphics
2    NVIDIA Geforce RTX 3050 4GB GDDR6 Intel UHD Gr...
3    NVIDIA GeForce RTX 4050 6GB GDDR6 (194 AI TOPs...
4                                    Intel HD Graphics
..                                                 ...
785   NVIDIA GeForce RTX 4090 16GB GDDR6 (686 AI TOPs)
786                                 Intel UHD Graphics
787    NVIDIA GeForce RTX 4070 (321 AI TOPs) 8GB GDDR6
788                 NVIDIA GeForce RTX 4090 16GB GDDR6
789                 NVIDIA GeForce RTX 4080 12GB GDDR6

                                               Storage  Screen Size  \
0    512GB PCIe 4.0 NVMe M.2 SSD (2 Khe cắm M.2 hỗ ...    16 inches
1                          SSD 512GB M.2 NVMe PCIe 3.0    14 inches
2                          512GB M.2 NVMe PCIe 4.0 SSD    16 inches
3                          512GB M.2 NVMe PCIe 4.0 SSD    16 inches
4                          512GB M.2 NVMe PCIe 4.0 SSD  15.6 inches
..                                                 ...          ...
785                          2TB PCIe 4.0 NVMe M.2 SSD    16 inches
786                   512GB M.2 2280 NVMe PCIe 4.0 SSD    14 inches
787  1TB PCIe 4.0 NVMe M.2 SSD 2x DDR5 SO-DIMM slot...    18 inches
788                          2TB PCIe 4.0 NVMe M.2 SSD    18 inches
789            2TB PCIe® 4.0 NVMe™ M.2 Performance SSD    16 inches

               Screen Resolution  Panel  Screen frequency  Weight  \
0     1920 x 1200 pixels (WUXGA)    NaN               NaN     NaN
1    1920 x 1080 pixels (FullHD)    NaN               NaN     NaN
2     1920 x 1200 pixels (WUXGA)    NaN               NaN     NaN
3     1920 x 1200 pixels (WUXGA)    NaN               NaN     NaN
4    1920 x 1080 pixels (FullHD)    NaN               NaN     NaN
..                           ...    ...               ...     ...
785      2560 x 1600 pixels (2K)    NaN               NaN     NaN
786  1920 x 1080 pixels (FullHD)    NaN               NaN     NaN
787      2560 x 1600 pixels (2K)    NaN               NaN     NaN
788          2560 x 1600 (WQXGA)    NaN               NaN     NaN
789          2560 x 1600 (WQXGA)    NaN               NaN     NaN

                                                   URL
0    https://cellphones.com.vn/laptop-asus-tuf-gami...
1    https://cellphones.com.vn/laptop-asus-vivobook...
2    https://cellphones.com.vn/laptop-asus-vivobook...
3    https://cellphones.com.vn/laptop-asus-gaming-v...
4    https://cellphones.com.vn/laptop-asus-vivobook...
..                                                 ...
785  https://cellphones.com.vn/laptop-asus-rog-stri...
786  https://cellphones.com.vn/laptop-asus-expertbo...
787  https://cellphones.com.vn/laptop-asus-rog-stri...
788  https://cellphones.com.vn/laptop-asus-gaming-r...
789  https://cellphones.com.vn/laptop-asus-gaming-r...

[790 rows x 12 columns]>